In [13]:
import pandas as pd

In [4]:
data = pd.read_csv("AAPL.csv")

print("Dataset loaded successfully")

Dataset loaded successfully

In [5]:
data.head()

         Date      Open      High       Low     Close  Adj Close     Volume
0  1980-12-12  0.128348  0.128906  0.128348  0.128348   0.100323  469033600
1  1980-12-15  0.122210  0.122210  0.121652  0.121652   0.095089  175884800
2  1980-12-16  0.113281  0.113281  0.112723  0.112723   0.088110  105728000
3  1980-12-17  0.115513  0.116071  0.115513  0.115513   0.090291   86441600
4  1980-12-18  0.118862  0.119420  0.118862  0.118862   0.092908   73449600

In [8]:
data["Daily Delta"] = data["Close"] - data["Open"]

data.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Daily Delta
0,1980-12-12,0.128348,0.128906,0.128348,0.128348,0.100323,469033600,0.000000
1,1980-12-15,0.122210,0.122210,0.121652,0.121652,0.095089,175884800,-0.000558
2,1980-12-16,0.113281,0.113281,0.112723,0.112723,0.088110,105728000,-0.000558
3,1980-12-17,0.115513,0.116071,0.115513,0.115513,0.090291,86441600,0.000000
4,1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092908,73449600,0.000000

In [9]:
top_10 = data[data["Daily Delta"] > 0].sort_values("Daily Delta", ascending=False).head(10)

print(top_10[["Date", "Open", "Close", "Daily Delta"]])

             Date        Open       Close  Daily Delta
10388  2022-02-24  152.580002  162.740005    10.160003
10028  2020-09-21  104.540001  110.080002     5.540001
10329  2021-11-30  159.990005  165.300003     5.309998
10008  2020-08-21  119.262497  124.370003     5.107506
10331  2021-12-02  158.740005  163.759995     5.019990
10371  2022-01-31  170.160004  174.779999     4.619995
10370  2022-01-28  165.710007  170.330002     4.619995
10043  2020-10-12  120.059998  124.400002     4.340004
10337  2021-12-10  175.210007  179.449997     4.239990
10401  2022-03-15  150.899994  155.089996     4.190002

In [11]:
data["Daily Return"] = ((data["Close"] - data["Open"]) / data["Open"]) * 100

data.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Daily Delta,Daily Return
0,1980-12-12,0.128348,0.128906,0.128348,0.128348,0.100323,469033600,0.000000,0.000000
1,1980-12-15,0.122210,0.122210,0.121652,0.121652,0.095089,175884800,-0.000558,-0.456591
2,1980-12-16,0.113281,0.113281,0.112723,0.112723,0.088110,105728000,-0.000558,-0.492580
3,1980-12-17,0.115513,0.116071,0.115513,0.115513,0.090291,86441600,0.000000,0.000000
4,1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092908,73449600,0.000000,0.000000

In [12]:
top_10_returns = data.sort_values("Daily Return", ascending=False).head(10)

print(top_10_returns[["Date", "Open", "Close", "Daily Return"]])

            Date      Open     Close  Daily Return
4312  1998-01-02  0.121652  0.145089     19.265610
4314  1998-01-06  0.142299  0.169085     18.823744
1739  1987-10-29  0.305804  0.352679     15.328446
4191  1997-07-11  0.119420  0.135603     13.551331
921   1984-08-03  0.107701  0.122210     13.471556
4267  1997-10-28  0.142857  0.161830     13.281113
4889  2000-04-17  0.977679  1.106027     13.127826
7022  2008-10-10  3.060714  3.457143     12.952174
5069  2001-01-03  0.258929  0.292411     12.930958
3492  1994-10-05  0.300223  0.338170     12.639605